# ProjectDuck 應用程式配置檔案
# YAML 語法高亮測試

app:
  name: ProjectDuck
  version: 1.0.0
  description: "Project Document 的諧音 - 一個專為文件檢視而設計的 Web 應用程式"
  
  # 伺服器配置
  server:
    host: localhost
    port: 3001
    cors:
      enabled: true
      origins:
        - http://localhost:3000
        - http://127.0.0.1:3000
    
    # 安全設定
    security:
      pathValidation: true
      maxFileSize: 10MB
      allowedExtensions:
        documents: [md, txt, pdf, doc, docx]
        code: [js, ts, jsx, tsx, py, java, cpp, c, go, rs, php, rb]
        data: [json, xml, yaml, yml, csv]
        styles: [css, scss, sass, less]
        markup: [html, htm, xml]
        config: [conf, ini, env, properties]
        media: [png, jpg, jpeg, gif, svg, webp, bmp, mp4, avi, mov]

  # 前端配置
  frontend:
    host: localhost 
    port: 3000
    
    # 主題設定
    theme:
      default: light
      modes: [light, dark]
      colors:
        primary: "#1890ff"
        success: "#52c41a"
        warning: "#faad14"
        error: "#ff4d4f"
      
      # 字型設定
      fonts:
        ui: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
        code: "Monaco, Consolas, 'Courier New', monospace"
        sizes:
          small: 12px
          normal: 14px
          large: 16px
          heading: 20px

    # 功能開關
    features:
      fileTree: true
      contentViewer: true
      syntaxHighlight: true
      markdownRendering: true
      themeToggle: true
      search: true
      mermaidCharts: true
      plantUMLCharts: false
      sectionCollapse: true

  # 日誌配置
  logging:
    level: info
    format: json
    outputs:
      console: 
        enabled: true
        colorize: true
      file:
        enabled: false
        path: ./logs/app.log
        maxSize: 10MB
        maxFiles: 5

  # 資料庫配置 (如果需要)
  database:
    enabled: false
    type: sqlite
    connection:
      host: localhost
      port: 5432
      database: projectduck
      username: user
      password: password
      ssl: false
    
    pool:
      min: 2
      max: 10
      idle: 10000

  # 快取配置
  cache:
    enabled: true
    type: memory
    ttl: 300 # 5 分鐘
    maxSize: 50MB
    
    # Redis 配置 (如果使用 Redis)
    redis:
      host: localhost
      port: 6379
      database: 0
      password: null

  # 監控配置
  monitoring:
    enabled: false
    metrics:
      enabled: false
      port: 9090
      path: /metrics
    
    health:
      enabled: true
      path: /health
      
    tracing:
      enabled: false
      jaeger:
        endpoint: http://localhost:14268/api/traces

# 開發環境設定
development:
  hotReload: true
  sourceMap: true
  debug: true
  mock:
    enabled: false
    delay: 100

# 生產環境設定
production:
  minify: true
  compression: true
  optimization:
    splitChunks: true
    treeShaking: true
  
  # CDN 設定
  cdn:
    enabled: false
    baseUrl: https://cdn.example.com
    
  # SSL/TLS 設定
  ssl:
    enabled: false
    cert: /path/to/cert.pem
    key: /path/to/key.pem

# 測試環境設定
test:
  database:
    type: sqlite
    connection: ":memory:"
  
  cache:
    enabled: false
    
  mock:
    enabled: true
    fixtures: ./tests/fixtures